function ok=writeXIoutput(opt,state,sampnum)

% ok=writeXIoutput(state,sampnum)
% writes the values of XI for each leaf in the file
% [opt.path opt.file]XI.txt

if nargin == 2
    sampnum = 0;
end

ok = 1;
if sampnum > 1
    % append
    fid = fopen([opt.path opt.file 'XI.txt'],'a');
else
    % write new
    fid = fopen([opt.path opt.file 'XI.txt'],'w');
end
if fid <= 0
    ok = 0;
    disp([opt.path opt.file 'XI.txt could not be opened to write XI output.'])
end

if ok
   if sampnum<=1
       % write header
       fprintf(fid,'#NEXUS\n\n[%1.0f samples from mcmc run generated by language trees. File written %s]\n',opt.Nsamp,datestr(clock));
       fprintf(fid,'[This file contains the values of XI at each leaf.]\n');
       fprintf(fid,'[For associated trees see same file with .nex extension]\n');
       fprintf(fid,'[Sample \t');
       for i=state.leaves
           fprintf(fid,'%s   \t',state.tree(i).Name);
       end
       fprintf(fid,']\n');
   end
   
   fprintf(fid,'  %10.0f \t',sampnum);
   for i=state.leaves
       fprintf(fid,'%1.8f \t',state.tree(i).xi);
   end
   fprintf(fid,'\n');
end

% close the file
ok = fclose(fid)==0;
if ~ok
    disp(['Could not close the XI file ', opt.path, opt.file, 'XI.txt', ' in writeXIoutput'])
    keyboard;
end
       
       
       
       
       
       