%My full setup, RJR, 28/02/07

clear all
close all

fsu=struct(...
    'BORROW',1,...
    'BORROWING', 1, ...
    'BORROWFRAC',.5,...
    'CLADEMASK',[],...
    'COLUMNMASK',[],...
    'DATAFILE','',...
    'DATAMASK',[],...
    'DATASOURCE',2,...
    'GUICONTENT',[],...
    'ISCOLMASK',0,...
    'ISCLADE',0,...
    'ISLRRANDOM',1,...
    'KAPPA',.2,...
    'LAMBDA',1.0,...
    'LOCALBORROW',0,...
    'LOSSRATE',.2,...
    'LOSSRATEBRANCHVAR',0,...
    'LOSSRATECLASSVAR',0,...
    'LOST',-1,...
    'LOSTONES',0,...
    'MASKING',0,...
    'MAXDIST',16000,...
    'MCMCCAT',1,...
    'MCMCINITBETA', 0.5, ...
    'MCMCINITKAPPA',.15,...
    'MCMCINITLAMBDA',1.5,...
    'MCMCINITMU',.35,...
    'MCMCINITNU',55,...
    'MCMCINITP',1,...
    'MCMCINITRHO',.15,...
    'MCMCINITTHETA',.015,...
    'MCMCINITTREE',[],...
    'MCMCINITTREEFILE',[],...
    'MCMCINITTREENUM',1,...
    'MCMCINITTREESTYLE',2,...
    'MCMCVARYTOP',1,...
    'MISDAT',0,...
    'NMEANINGCLASS',4,...
    'NU',3,...
    'NUMSEQ',4,...
    'OUTFILE','myoutfile',...
    'OUTPATH','',...
    'POLYMORPH',0,...
    'PSURVIVE',1,...
    'RHO',.1,...
    'ROOTMAX',16000,...
    'RUNLENGTH',1000,...
    'SEED',0,...
    'SEEDRAND',0,...
    'SUBSAMPLE',20,...
    'SYNTHSTYLE',2,...
    'SYNTHTRE',1,...
    'SYNTHTREFILE','',...
    'THETA',.1,...
    'TREEPRIOR',2,...
    'VARYBETA', 1, ...
    'VARYKAPPA',1,...
    'VARYLAMBDA',1,...
    'VARYMU',1,...
    'VARYNU',1,...
    'VARYP',0,...
    'VARYRHO',1,...
    'VERBOSE',2,...
    'VOCABSIZE',5);

    